// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnWkTj3ghcdVO0CWOh3V-N9LktSa52DDs',
    appId: '1:139154283419:web:b3abdeee54b07d371f9f3e',
    messagingSenderId: '139154283419',
    projectId: 'agendaaitorfirebase',
    authDomain: 'agendaaitorfirebase.firebaseapp.com',
    storageBucket: 'agendaaitorfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZiIEbJulXjiwaGarTnwFohDiSCTBQkf8',
    appId: '1:139154283419:android:48db594ebc9629f21f9f3e',
    messagingSenderId: '139154283419',
    projectId: 'agendaaitorfirebase',
    storageBucket: 'agendaaitorfirebase.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnWkTj3ghcdVO0CWOh3V-N9LktSa52DDs',
    appId: '1:139154283419:web:2ddd6661b438d77e1f9f3e',
    messagingSenderId: '139154283419',
    projectId: 'agendaaitorfirebase',
    authDomain: 'agendaaitorfirebase.firebaseapp.com',
    storageBucket: 'agendaaitorfirebase.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6cPDvhV8scvlftoZmheCMNPVxsIqpyzU',
    appId: '1:139154283419:ios:901bb5ed68287b501f9f3e',
    messagingSenderId: '139154283419',
    projectId: 'agendaaitorfirebase',
    storageBucket: 'agendaaitorfirebase.firebasestorage.app',
    iosBundleId: 'com.example.agenda',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6cPDvhV8scvlftoZmheCMNPVxsIqpyzU',
    appId: '1:139154283419:ios:901bb5ed68287b501f9f3e',
    messagingSenderId: '139154283419',
    projectId: 'agendaaitorfirebase',
    storageBucket: 'agendaaitorfirebase.firebasestorage.app',
    iosBundleId: 'com.example.agenda',
  );
}
